import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { assertSafeIdentifier, type Operation, type Target } from '@ghostapi/core';
import { readTemplate } from './templates.js';
import { selectForExport, type SelectionOptions, type SelectionResult } from './select.js';
import { inputTypeName, outputTypeName, renderType } from './ts-types.js';

export interface TsExportOptions extends SelectionOptions {
  readonly target: Target;
  readonly operations: readonly Operation[];
  readonly outDir: string;
}

export interface TsExportResult {
  readonly outDir: string;
  readonly files: string[];
  readonly selection: SelectionResult;
}

function docComment(operation: Operation): string {
  return [
    '/**',
    ` * ${operation.description.replace(/\*\//g, '*\\/')}`,
    ' *',
    ` * Confidence ${Math.round(operation.confidence * 100)}% from ${operation.observationCount} observation(s).`,
    ...(operation.destructive ? [' *', ' * @remarks This operation is destructive.'] : []),
    ' */',
  ].join('\n  ');
}

/**
 * Emits a typed client.
 *
 * The generated code is plain TypeScript over `fetch` with no GhostAPI runtime
 * dependency, so it can be dropped into any project. Types come from the
 * inferred schemas, which means the compiler enforces exactly what the evidence
 * supports — no more.
 */
export async function exportTypescript(options: TsExportOptions): Promise<TsExportResult> {
  const selection = selectForExport(options.operations, options);
  const outDir = options.outDir;
  await mkdir(outDir, { recursive: true });

  const files: string[] = [];
  const write = async (name: string, content: string): Promise<void> => {
    await writeFile(join(outDir, name), content, 'utf8');
    files.push(name);
  };

  const typeLines = selection.selected.flatMap((operation) => {
    const name = assertSafeIdentifier(operation.name, 'operation name');
    const lines = [`export interface ${inputTypeName(operation)} ${renderType(operation.inputs)}`, ''];
    if (operation.output && Object.keys(operation.output).length > 0) {
      lines.push(`export type ${outputTypeName(operation)} = ${renderType(operation.output)};`, '');
    } else {
      lines.push(`export type ${outputTypeName(operation)} = unknown;`, '');
    }
    void name;
    return lines;
  });

  await write(
    'types.ts',
    [
      `// Generated by GhostAPI from observed traffic on ${options.target.origin}.`,
      '// Do not edit by hand; re-run `ghostapi export ts`.',
      '',
      ...typeLines,
    ].join('\n'),
  );

  const methods = selection.selected.map((operation) => {
    const name = assertSafeIdentifier(operation.name, 'operation name');
    const hasInputs = Object.keys(operation.inputs.properties ?? {}).length > 0;
    const signature = hasInputs
      ? `input: T.${inputTypeName(operation)}`
      : `input: T.${inputTypeName(operation)} = {}`;
    return [
      `  ${docComment(operation)}`,
      `  async ${name}(${signature}): Promise<T.${outputTypeName(operation)}> {`,
      `    const result = await this.call('${name}', input as unknown as Record<string, unknown>);`,
      `    return result.data as T.${outputTypeName(operation)};`,
      '  }',
    ].join('\n');
  });

  await write(
    'client.ts',
    [
      `// Generated by GhostAPI from observed traffic on ${options.target.origin}.`,
      '// Do not edit by hand; re-run `ghostapi export ts`.',
      "import operations from './operations.json' with { type: 'json' };",
      "import { executeOperation, type ExecutionOutcome, type OperationLike } from './runtime.js';",
      "import type * as T from './types.js';",
      '',
      'const catalogue = operations.operations as unknown as OperationLike[];',
      '',
      'export interface GhostClientOptions {',
      '  /** Cookie header for targets authenticated by a browser session. */',
      '  cookie?: string;',
      '  /** Overrides process.env when resolving header credentials. */',
      '  env?: Record<string, string | undefined>;',
      '  /** Replaces the global fetch, for tests or a custom agent. */',
      '  fetchImpl?: typeof fetch;',
      '  /** Allows operations marked destructive. Off by default. */',
      '  allowDestructive?: boolean;',
      '}',
      '',
      `export class ${className(options.target.slug)} {`,
      '  private readonly options: GhostClientOptions;',
      '',
      '  constructor(options: GhostClientOptions = {}) {',
      '    this.options = options;',
      '  }',
      '',
      '  private async call(name: string, input: Record<string, unknown>): Promise<ExecutionOutcome> {',
      '    const operation = catalogue.find((candidate) => candidate.name === name);',
      '    if (!operation) throw new Error(`Unknown operation "${name}"`);',
      '    if (operation.destructive && this.options.allowDestructive !== true) {',
      '      throw new Error(`"${name}" is destructive. Construct the client with { allowDestructive: true } to call it.`);',
      '    }',
      '    return executeOperation(operation, input, this.options);',
      '  }',
      '',
      ...methods,
      '}',
      '',
      `export function createGhostClient(options: GhostClientOptions = {}): ${className(options.target.slug)} {`,
      `  return new ${className(options.target.slug)}(options);`,
      '}',
      '',
      "export type * from './types.js';",
      '',
    ].join('\n'),
  );

  await write('runtime.ts', await readTemplate('ts-runtime.ts'));
  // The generated client is ESM and imports JSON with an import attribute,
  // which only resolves when the directory declares itself a module.
  await write(
    'package.json',
    `${JSON.stringify(
      {
        name: `ghostapi-client-${options.target.slug}`,
        version: '0.1.0',
        private: true,
        type: 'module',
        main: './client.ts',
      },
      null,
      2,
    )}\n`,
  );
  await write(
    'tsconfig.json',
    `${JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'NodeNext',
          moduleResolution: 'NodeNext',
          strict: true,
          noEmit: true,
          skipLibCheck: true,
          resolveJsonModule: true,
          lib: ['ES2023', 'DOM'],
        },
        include: ['*.ts'],
      },
      null,
      2,
    )}\n`,
  );
  await write(
    'operations.json',
    `${JSON.stringify(
      {
        targetSlug: options.target.slug,
        targetOrigin: options.target.origin,
        generatedAt: new Date().toISOString(),
        operations: selection.selected.map((operation) => ({
          name: operation.name,
          description: operation.description,
          inputs: operation.inputs,
          transport: operation.transport,
          fallbacks: operation.fallbacks,
          auth: operation.auth,
          destructive: operation.destructive,
        })),
      },
      null,
      2,
    )}\n`,
  );

  await write(
    'README.md',
    [
      `# ${options.target.name} client`,
      '',
      'Generated by GhostAPI. Plain TypeScript over `fetch`, no runtime dependency.',
      '',
      '```ts',
      "import { createGhostClient } from './client.js';",
      '',
      'const client = createGhostClient({ cookie: process.env.SESSION_COOKIE });',
      '',
      ...(selection.selected[0]
        ? [
            `const result = await client.${selection.selected[0].name}(${exampleInput(selection.selected[0])});`,
          ]
        : []),
      '```',
      '',
      'This directory contains no credentials. Pass a cookie explicitly, or set the environment',
      'variable each operation names for header-based authentication.',
      '',
    ].join('\n'),
  );

  return { outDir, files, selection };
}

function className(slug: string): string {
  const pascal = slug
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  // A slug can start with a digit (an IP, a version), which is not a legal
  // TypeScript identifier. Prefix rather than silently emitting broken code.
  const safe = /^[A-Za-z]/.test(pascal) ? pascal : `Ghost${pascal}`;
  return `${safe || 'Ghost'}Client`;
}

function exampleInput(operation: Operation): string {
  const properties = operation.inputs.properties ?? {};
  const required = operation.inputs.required ?? [];
  const entries = required.slice(0, 3).map((key) => {
    const schema = properties[key];
    const example = schema?.examples?.[0] ?? (schema?.enum?.[0] as unknown) ?? 'value';
    return `${key}: ${JSON.stringify(example)}`;
  });
  return entries.length > 0 ? `{ ${entries.join(', ')} }` : '{}';
}
