#!/usr/bin/env node
// Generated by GhostAPI. A stdio MCP server exposing discovered operations.
//
// No credentials live in this directory. Auth is resolved at call time from the
// environment or from the local GhostAPI session store.
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import { executeOperation } from './runtime.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(await readFile(join(here, 'operations.json'), 'utf8'));
const operations = new Map(manifest.operations.map((operation) => [operation.name, operation]));

const server = new Server(
  { name: manifest.serverName, version: manifest.version },
  { capabilities: { tools: {} } },
);

const tools = manifest.operations.map((operation) => ({
  name: operation.name,
  description: operation.description,
  inputSchema: {
    type: 'object',
    properties: operation.inputs?.properties ?? {},
    required: operation.inputs?.required ?? [],
    additionalProperties: false,
  },
  annotations: {
    title: operation.title ?? operation.name,
    readOnlyHint: operation.readOnly === true,
    destructiveHint: operation.destructive === true,
    idempotentHint: operation.idempotent === true,
    openWorldHint: true,
  },
}));

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools }));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const operation = operations.get(request.params.name);
  if (!operation) {
    return {
      isError: true,
      content: [{ type: 'text', text: `Unknown operation "${request.params.name}".` }],
    };
  }
  if (operation.destructive && process.env.GHOSTAPI_ALLOW_DESTRUCTIVE !== '1') {
    return {
      isError: true,
      content: [
        {
          type: 'text',
          text:
            `"${operation.name}" is marked destructive and is blocked by default.\n` +
            'Set GHOSTAPI_ALLOW_DESTRUCTIVE=1 in this MCP server\'s environment to allow it.',
        },
      ],
    };
  }
  try {
    const result = await executeOperation(operation, request.params.arguments ?? {}, {
      slug: manifest.targetSlug,
    });
    return {
      content: [{ type: 'text', text: JSON.stringify(result.data, null, 2) }],
      structuredContent: { status: result.status, latencyMs: result.latencyMs, data: result.data },
    };
  } catch (error) {
    return {
      isError: true,
      content: [{ type: 'text', text: error instanceof Error ? error.message : String(error) }],
    };
  }
});

await server.connect(new StdioServerTransport());
