// Generated by GhostAPI. Portable replay runtime for exported operations.
//
// This file contains no credentials. Operations reference their auth
// abstractly; the values are resolved here, at run time, from the environment
// or from the local GhostAPI session store.
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

export function resolveBinding(binding, inputs) {
  if (!binding) return undefined;
  switch (binding.kind) {
    case 'literal':
      return binding.value;
    case 'input':
      return inputs[binding.field];
    case 'array':
      return binding.items.map((item) => resolveBinding(item, inputs));
    case 'object': {
      const out = {};
      for (const [key, child] of Object.entries(binding.properties)) {
        const value = resolveBinding(child, inputs);
        if (value !== undefined) out[key] = value;
      }
      return out;
    }
    default:
      return undefined;
  }
}

export function fillUrlTemplate(template, params, inputs) {
  let url = template;
  for (const param of params) {
    const value = inputs[param];
    if (value === undefined || value === null || value === '') {
      throw new Error(`Missing path parameter "${param}"`);
    }
    url = url.split(`{${param}}`).join(encodeURIComponent(String(value)));
  }
  return url;
}

export function validateInputs(inputs, schema) {
  const issues = [];
  const properties = schema?.properties ?? {};
  for (const key of schema?.required ?? []) {
    if (inputs[key] === undefined) issues.push(`${key} is required`);
  }
  for (const [key, value] of Object.entries(inputs)) {
    const child = properties[key];
    if (!child) {
      if (schema?.additionalProperties === false) issues.push(`${key} is not an input of this operation`);
      continue;
    }
    if (child.enum && !child.enum.includes(value)) {
      issues.push(`${key} must be one of ${child.enum.join(', ')}`);
    }
  }
  return issues;
}

async function readStoredCookies(slug) {
  const home = process.env.GHOSTAPI_HOME;
  if (!home) return [];
  try {
    const raw = await readFile(join(home, 'targets', slug, 'auth.json'), 'utf8');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed.cookies) ? parsed.cookies : [];
  } catch {
    return [];
  }
}

export async function resolveAuthHeaders(auth, slug) {
  if (!auth || auth.strategy === 'none') return {};
  if (auth.strategy === 'header') {
    const value = process.env[auth.env];
    if (!value) {
      throw new Error(
        `Missing credential: set ${auth.env} in the environment. GhostAPI never stores it.`,
      );
    }
    return { [auth.header.toLowerCase()]: `${auth.prefix ?? ''}${value}` };
  }
  if (auth.strategy === 'cookie') {
    const value = process.env[auth.env];
    if (!value) throw new Error(`Missing credential: set ${auth.env} in the environment.`);
    return { cookie: value };
  }
  // browser-session
  const explicit = process.env.GHOSTAPI_COOKIE;
  if (explicit) return { cookie: explicit };
  const cookies = await readStoredCookies(slug);
  if (cookies.length === 0) {
    throw new Error(
      'No browser session available. Run `ghostapi open <url>` and sign in, or set GHOSTAPI_COOKIE.',
    );
  }
  return { cookie: cookies.map((cookie) => `${cookie.name}=${cookie.value}`).join('; ') };
}

export async function executeOperation(operation, inputs, options = {}) {
  const slug = options.slug ?? '';
  const issues = validateInputs(inputs, operation.inputs);
  if (issues.length > 0) throw new Error(`Invalid input: ${issues.join('; ')}`);

  const transports = [operation.transport, ...(operation.fallbacks ?? [])];
  const transport = transports.find((candidate) => candidate.type === 'http' || candidate.type === 'graphql');
  if (!transport) {
    throw new Error(
      `${operation.name} has no HTTP transport. Browser-only operations must be run through the GhostAPI CLI.`,
    );
  }

  const authHeaders = await resolveAuthHeaders(operation.auth, slug);
  const startedAt = Date.now();

  if (transport.type === 'graphql') {
    const variables = {};
    for (const [key, binding] of Object.entries(transport.variables ?? {})) {
      const value = resolveBinding(binding, inputs);
      if (value !== undefined) variables[key] = value;
    }
    const response = await fetch(transport.endpoint, {
      method: 'POST',
      headers: { 'content-type': 'application/json', ...authHeaders },
      body: JSON.stringify({
        query: transport.document,
        ...(transport.operationName ? { operationName: transport.operationName } : {}),
        variables,
      }),
    });
    const data = await response.json().catch(() => null);
    if (!response.ok) throw new Error(`${transport.endpoint} returned ${response.status}`);
    if (data?.errors?.length) throw new Error(data.errors.map((e) => e.message).join('; '));
    return { status: response.status, data, latencyMs: Date.now() - startedAt, transport: 'graphql' };
  }

  const base = fillUrlTemplate(transport.urlTemplate, transport.pathParams ?? [], inputs);
  const url = new URL(base);
  for (const [key, binding] of Object.entries(transport.query ?? {})) {
    const value = resolveBinding(binding, inputs);
    if (value === undefined || value === null || value === '') continue;
    url.searchParams.set(key, String(value));
  }

  const headers = { ...authHeaders };
  for (const [name, binding] of Object.entries(transport.headers ?? {})) {
    if (binding.kind === 'literal') headers[name.toLowerCase()] = binding.value;
    else if (binding.kind === 'input' && inputs[binding.field] !== undefined) {
      headers[name.toLowerCase()] = String(inputs[binding.field]);
    } else if (binding.kind === 'env' && process.env[binding.env]) {
      headers[name.toLowerCase()] = `${binding.prefix ?? ''}${process.env[binding.env]}`;
    }
  }

  let body;
  if (transport.body && transport.bodyKind !== 'none') {
    const value = resolveBinding(transport.body, inputs);
    if (transport.bodyKind === 'form') {
      body = new URLSearchParams(Object.entries(value ?? {}).map(([k, v]) => [k, String(v)])).toString();
      headers['content-type'] ??= 'application/x-www-form-urlencoded';
    } else {
      body = JSON.stringify(value);
      headers['content-type'] ??= 'application/json';
    }
  }

  const response = await fetch(url.toString(), { method: transport.method, headers, body });
  const text = await response.text();
  let data = text.length === 0 ? null : text;
  if ((response.headers.get('content-type') ?? '').includes('json') && text.length > 0) {
    try {
      data = JSON.parse(text);
    } catch {
      /* keep the text */
    }
  }
  if (!response.ok) {
    const hint =
      response.status === 401 || response.status === 403
        ? ' The session used to derive this operation may have expired; run `ghostapi open <url>` and sign in again.'
        : '';
    throw new Error(`${transport.method} ${url.pathname} returned ${response.status}.${hint}`);
  }
  return { status: response.status, data, latencyMs: Date.now() - startedAt, transport: 'http' };
}
