// Generated by GhostAPI. Portable replay runtime for the typed client.
//
// Contains no credentials. Operations reference their auth abstractly; values
// are resolved here at call time.
//
// No dependencies, including @types/node: the client is meant to drop into any
// project, browser bundles included, so `process` is declared rather than
// imported.
declare const process: { env: Record<string, string | undefined> } | undefined;

export type ValueBinding =
  | { kind: 'literal'; value?: unknown }
  | { kind: 'input'; field: string }
  | { kind: 'object'; properties: Record<string, ValueBinding> }
  | { kind: 'array'; items: ValueBinding[] };

export type HeaderBinding =
  | { kind: 'literal'; value: string }
  | { kind: 'input'; field: string }
  | { kind: 'env'; env: string; prefix?: string }
  | { kind: 'session' };

export type AuthStrategy =
  | { strategy: 'none' }
  | { strategy: 'browser-session'; cookieNames?: string[] }
  | { strategy: 'header'; header: string; env: string; prefix?: string }
  | { strategy: 'cookie'; env: string };

export interface HttpTransport {
  type: 'http';
  method: string;
  urlTemplate: string;
  pathParams?: string[];
  query?: Record<string, ValueBinding>;
  headers?: Record<string, HeaderBinding>;
  bodyKind?: string;
  body?: ValueBinding;
}

export interface GraphQLTransport {
  type: 'graphql';
  endpoint: string;
  operationName?: string;
  document: string;
  variables?: Record<string, ValueBinding>;
  headers?: Record<string, HeaderBinding>;
}

export interface OperationLike {
  name: string;
  description: string;
  inputs: {
    properties?: Record<string, unknown>;
    required?: string[];
    additionalProperties?: boolean;
  };
  transport: HttpTransport | GraphQLTransport | { type: string };
  fallbacks?: ({ type: string } | HttpTransport | GraphQLTransport)[];
  auth: AuthStrategy;
  destructive: boolean;
}

export interface ExecutionOutcome {
  status: number;
  data: unknown;
  latencyMs: number;
  transport: 'http' | 'graphql';
}

export interface RuntimeOptions {
  cookie?: string;
  env?: Record<string, string | undefined>;
  fetchImpl?: typeof fetch;
}

export function resolveBinding(
  binding: ValueBinding | undefined,
  inputs: Record<string, unknown>,
): unknown {
  if (!binding) return undefined;
  switch (binding.kind) {
    case 'literal':
      return binding.value;
    case 'input':
      return inputs[binding.field];
    case 'array':
      return binding.items.map((item) => resolveBinding(item, inputs));
    case 'object': {
      const out: Record<string, unknown> = {};
      for (const [key, child] of Object.entries(binding.properties)) {
        const value = resolveBinding(child, inputs);
        if (value !== undefined) out[key] = value;
      }
      return out;
    }
  }
}

export function fillUrlTemplate(
  template: string,
  params: readonly string[],
  inputs: Record<string, unknown>,
): string {
  let url = template;
  for (const param of params) {
    const value = inputs[param];
    if (value === undefined || value === null || value === '') {
      throw new Error(`Missing path parameter "${param}"`);
    }
    url = url.split(`{${param}}`).join(encodeURIComponent(String(value)));
  }
  return url;
}

function resolveAuthHeaders(auth: AuthStrategy, options: RuntimeOptions): Record<string, string> {
  const env = options.env ?? (typeof process !== 'undefined' ? process.env : {});
  switch (auth.strategy) {
    case 'none':
      return {};
    case 'browser-session': {
      if (!options.cookie) {
        throw new Error(
          'This operation replays a browser session. Pass { cookie } when creating the client.',
        );
      }
      return { cookie: options.cookie };
    }
    case 'header': {
      const value = env[auth.env];
      if (!value) throw new Error(`Missing credential: set ${auth.env} in the environment.`);
      return { [auth.header.toLowerCase()]: `${auth.prefix ?? ''}${value}` };
    }
    case 'cookie': {
      const value = options.cookie ?? env[auth.env];
      if (!value) throw new Error(`Missing credential: set ${auth.env} in the environment.`);
      return { cookie: value };
    }
  }
}

function headerValue(
  binding: HeaderBinding,
  inputs: Record<string, unknown>,
  env: Record<string, string | undefined>,
): string | undefined {
  switch (binding.kind) {
    case 'literal':
      return binding.value;
    case 'input': {
      const value = inputs[binding.field];
      return value === undefined ? undefined : String(value);
    }
    case 'env': {
      const value = env[binding.env];
      return value === undefined ? undefined : `${binding.prefix ?? ''}${value}`;
    }
    case 'session':
      return undefined;
  }
}

function validate(inputs: Record<string, unknown>, schema: OperationLike['inputs']): void {
  const issues: string[] = [];
  for (const key of schema.required ?? []) {
    if (inputs[key] === undefined) issues.push(`${key} is required`);
  }
  if (issues.length > 0) throw new Error(`Invalid input: ${issues.join('; ')}`);
}

export async function executeOperation(
  operation: OperationLike,
  inputs: Record<string, unknown>,
  options: RuntimeOptions = {},
): Promise<ExecutionOutcome> {
  validate(inputs, operation.inputs);
  const candidates = [operation.transport, ...(operation.fallbacks ?? [])];
  const transport = candidates.find(
    (candidate): candidate is HttpTransport | GraphQLTransport =>
      candidate.type === 'http' || candidate.type === 'graphql',
  );
  if (!transport) {
    throw new Error(
      `${operation.name} has no HTTP transport. Browser-only operations must be run through the GhostAPI CLI.`,
    );
  }

  const doFetch = options.fetchImpl ?? fetch;
  const env = options.env ?? (typeof process !== 'undefined' ? process.env : {});
  const authHeaders = resolveAuthHeaders(operation.auth, options);
  const startedAt = Date.now();

  if (transport.type === 'graphql') {
    const variables: Record<string, unknown> = {};
    for (const [key, binding] of Object.entries(transport.variables ?? {})) {
      const value = resolveBinding(binding, inputs);
      if (value !== undefined) variables[key] = value;
    }
    const response = await doFetch(transport.endpoint, {
      method: 'POST',
      headers: { 'content-type': 'application/json', ...authHeaders },
      body: JSON.stringify({
        query: transport.document,
        ...(transport.operationName ? { operationName: transport.operationName } : {}),
        variables,
      }),
    });
    const data = (await response.json().catch(() => null)) as {
      errors?: { message?: string }[];
    } | null;
    if (!response.ok) throw new Error(`${transport.endpoint} returned ${response.status}`);
    if (data?.errors?.length) {
      throw new Error(data.errors.map((error) => error.message ?? 'error').join('; '));
    }
    return {
      status: response.status,
      data,
      latencyMs: Date.now() - startedAt,
      transport: 'graphql',
    };
  }

  const url = new URL(fillUrlTemplate(transport.urlTemplate, transport.pathParams ?? [], inputs));
  for (const [key, binding] of Object.entries(transport.query ?? {})) {
    const value = resolveBinding(binding, inputs);
    if (value === undefined || value === null || value === '') continue;
    url.searchParams.set(key, String(value));
  }

  const headers: Record<string, string> = { ...authHeaders };
  for (const [name, binding] of Object.entries(transport.headers ?? {})) {
    const value = headerValue(binding, inputs, env);
    if (value !== undefined) headers[name.toLowerCase()] = value;
  }

  let body: string | undefined;
  if (transport.body && transport.bodyKind && transport.bodyKind !== 'none') {
    const value = resolveBinding(transport.body, inputs);
    if (transport.bodyKind === 'form') {
      const pairs: [string, string][] = Object.entries(
        (value ?? {}) as Record<string, unknown>,
      ).map(([key, item]) => [key, String(item)]);
      body = new URLSearchParams(pairs).toString();
      headers['content-type'] ??= 'application/x-www-form-urlencoded';
    } else {
      body = JSON.stringify(value);
      headers['content-type'] ??= 'application/json';
    }
  }

  const response = await doFetch(url.toString(), { method: transport.method, headers, body });
  const text = await response.text();
  let data: unknown = text.length === 0 ? null : text;
  if ((response.headers.get('content-type') ?? '').includes('json') && text.length > 0) {
    try {
      data = JSON.parse(text);
    } catch {
      /* keep the text */
    }
  }
  if (!response.ok) {
    const hint =
      response.status === 401 || response.status === 403
        ? ' The session used to derive this operation may have expired.'
        : '';
    throw new Error(`${transport.method} ${url.pathname} returned ${response.status}.${hint}`);
  }
  return { status: response.status, data, latencyMs: Date.now() - startedAt, transport: 'http' };
}
